### ISSUE TITLE
How are you obtaining the firmware .bin files?

### ISSUE THREAD

**Issue by ChrisLane** [geoffreybennett/scarlett2-firmware#1]
I'm just interested to know how you're getting the files in case I or anyone else would like to grab them manually.

**Comment by geoffreybennett** [comment]
Hi Chris,

This repo is the official location for Linux users to get firmware for their Scarlett/Clarett/Vocaster units. There is no other upstream source for these files, and you should treat them as a binary blob black box. Focusrite very kindly gave me permission to distribute these files under this license: https://github.com/geoffreybennett/scarlett2-firmware/blob/master/LICENSE.Focusrite

Focusrite don't offer support to end-users running Linux, so I've made it as difficult as I can for you to brick your device. If you try loading some firmware image onto your device that you didn't get from here and your device ends up broken, I'm going to say that you get to keep both pieces.

That said, actually answering your question now: you can see how I put these files together by looking at the `scarlett2` source; in `scarlett2-firmware.h`, it's pretty simple. The raw firmware files for Scarlett Gen 2/3 and Clarett are there for the taking when you install Focusrite Control. Gen 4 (Focusrite Control 2) and Vocaster (Vocaster Hub), you need to snoop the USB bus to grab the file as it goes by when you do a firmware upgrade.

Regards,
Geoffrey.

**Comment by ChrisLane** [comment]
I see, thanks for the info!
